image: gradle:8.12-jdk-alpine

stages:
    - test-stage
    - build-stage

build-backend:
    stage: build-stage
    script:
        - cd backend/api
        - gradle build

run-unittests:
    stage: test-stage 
    script:
        - cd backend/api
        - gradle test

api-test-coverage:
    stage: test-stage
    script:
        - cd backend/api
        - ': script'
        - chmod +x ../gradlew
        - ../gradlew check
        - cat build/jacocoHtml/index.html | grep -o '<tfoot>.*</tfoot>'
    coverage: '/Total.*?([0-9]{1,3})%/'

domain-test-coverage:
    stage: test-stage
    script:
        - cd backend/domain
        - ': script'
        - chmod +x ../gradlew
        - ../gradlew check
        - cat build/jacocoHtml/index.html | grep -o '<tfoot>.*</tfoot>'
    coverage: '/Total.*?([0-9]{1,3})%/'

persistence-test-coverage:
    stage: test-stage
    script:
        - cd backend/persistence
        - ': script'
        - chmod +x ../gradlew
        - ../gradlew check
        - cat build/jacocoHtml/index.html | grep -o '<tfoot>.*</tfoot>'
    coverage: '/Total.*?([0-9]{1,3})%/'
