# Comments are provided throughout this file to help you get started.
# If you need more help, visit the Docker compose reference guide at
# https://docs.docker.com/compose/compose-file/

# Here the instructions define your application as two services called "todo-app" and “todo-database”
# The service “todo-app” is built from the Dockerfile in the /app directory,
# and the service “todo-database” uses the official MongoDB image 
# from Docker Hub - https://hub.docker.com/_/mongo. 
# You can add other services your application may depend on here.

services:
  mancala-client:
    build:
      context: ./client
    # depends_on:
    #   - mancala-api
    environment:
      NODE_ENV: development
    ports:
      - 5173:5173
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client
          target: /usr/src/client
          action: sync

  # mancala-api:
  #   build:
  #     context: ./api
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 8080:8080

  # todo-database:
  #   image: mongo:6
  #   #volumes: 
  #   #  - database:/data/db
  #   ports:
  #     - 27017:27017

#volumes:
  #database: