plugins {
    // Tell Gradle that we are builing java as a library (non-executable piece of code intended for use by other applications).
    id 'java'
    id 'java-library'
    id 'com.adarshr.test-logger' version '4.0.0'
    id 'jacoco'
    id 'checkstyle'
}

repositories {
    // Specify the repository mirror that we want to download our dependencies from. Maven Central is configured by default when creating a new Gradle project.
    mavenCentral()
}

dependencies {
    // Download JUnit so that we can use it in our tests.
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.2'
    testRuntimeOnly "org.junit.platform:junit-platform-commons:1.8.2"
}

test {
    // For running our tests, use the test runner provided by JUnit.
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test // tests are required to run before generating the report
    reports {
        xml.required = false
        csv.required = false
        html.outputLocation = layout.buildDirectory.dir('jacocoHtml')
    }
}

checkstyle {
    toolVersion '10.21.2'
    configFile file("../config/checkstyle/checkstyle.xml")
        reportsDir = file("$project.rootDir/reports/checkstyle/$project.name")
    tasks.withType(Checkstyle) {
        reports {
            xml.required = true
            html.required = true
        }
    }
}

// checkstyleMain << {
//         ant.xslt(in: file("$project.rootDir/reports/checkstyle/$project.name/main.xml"),
//                 out: rootProject.file('config/aggregated.html'))
// }
